sudo: false
os: linux
language: node_js
node_js: node

cache:
  directories:
    - node_modules

env: ELM_VERSION=0.19.0

install:
  - npm install

script:
  - travis_retry npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
